### ISSUE TITLE
Weird output in Backup file 

### ISSUE THREAD

**Issue by Karl-WE** [MysticFoxDE/WINDOWS-OPTIMIZATIONS#16]
I believe it's a good idea to look into the Backup file
The content contains whitespaces galore.

I would appreciate the following method

- every value to be changed should be output  to the log by get-...
- you can use start-transscript to record console outputs if you don't want to handle dozends of variables.
-functions would come handy to avoid redundant code, but this idea has been declined. #10

**Comment by MysticFoxDE** [comment]
Hi Karl,

the whitespace comes from the standard output of PowerShell's Get commands and I don't think it's really annoying.
Also, I don't really want to "bloat" the code further with cosmetic improvements, because that makes it more and more incomprehensible for the majority. Incidentally, for the same reason, I also rejected the proposal regarding the functions.

Karl, I'm not concerned here with the perfect code, but rather with the botch that is "corrected" by it. And in order for the latter to be properly understood by the masses, I have to follow the "keep it simple, keep it smart" strategy as best I can, otherwise the whole thing will get to much too derailed.

Best Regards from BaWü
Alex

**Comment by MysticFoxDE** [comment]
PS
The next step is definitely to give the script some kind of change log function.
But I don't even have the time for that at the moment, and there are still problems with certain versions of Windows 10 when setting a certain and very important registry key. 🤢😭

**Comment by MysticFoxDE** [comment]
Moin Karl,

hast du das Thema mit dem TCP und WINSOCK Reset mitbekommen?
(Werkseinstellungen nicht gleich Reseteinstellungen)
Ist echt krank, aber mir fehlt aktuell absolut die Zeit das tiefer zu erforschen.

Gruss Alex

**Comment by MysticFoxDE** [comment]
Hi Karl,
ich habe die Backuproutine in der Version 1.15 überarbeitet und habe auf deren "Ausgabe" nun nicht wirklich einen Einfluss, da diese per "Start-Transcript/Stop-Transcript" nun über das ganze Skript erzeugt wird.
Vorteil davon ist jedoch, dass dadurch auch gleich eine Art Änderungslog mit erstellt wird. 😁
Aus diesem Grund würde ich diese Issue auch gerne schliessen.

By the Way.
Seit der Version 1.15, erzeugt das Skript auch gleich ein paar Registrybackups. 😎

Beste Grüsse aus BaWü
Alex
